import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveAppBar from "./components/layout/header";
import Container from "@mui/material/Container";
import AppBar from "@mui/material/AppBar";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <ResponsiveAppBar />
        <main>
          <Container sx={{ bgcolor: "white", marginY: 5, paddingY: 2 }}>
            {children}
          </Container>
        </main>
      </body>
    </html>
  );
}
